# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_form',
            name='file',
            field=models.CharField(max_length=100),
        ),
    ]
