# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20170901_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_form',
            old_name='file',
            new_name='file1',
        ),
    ]
